### ISSUE TITLE
🐛 Bug: Search Doesn't Work

### ISSUE THREAD

**Issue by jcserv** [utm-cssc/website#163]
### Expected Behavior 🧭
After typing in text, the most relevant pages/content on the website should be shown as search results. The user should then be able to select one to be redirected to the accompanying page.

### Current Behavior 🔍 

No search results appear

### Steps to Reproduce 🔢 

(Please write your answer here.)

1. Type something in search bar
2. Wait for nothing to happen

### Possible Solution 🛠️ 

Algolia is an option!

**Comment by hiimchrislim** [comment]
The search bar originally indexed on the resource pages but I believe Arsala changed it to where it indexes based on the category/topic that the resource pages are under.
(i.e. If you type web (since it's a category), resources that fall under that category will appear)

![image](https://user-images.githubusercontent.com/24628243/123874602-6e63d680-d906-11eb-977d-6ac71fd66fb9.png)

**Comment by jcserv** [comment]
Sweet, glad that it’s not broken but it could definitely be improved
